"""create tables

Revision ID: 467f0650e26a
Revises: fddbf015b39d
Create Date: 2023-06-20 11:13:04.741811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467f0650e26a'
down_revision = 'fddbf015b39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_missions_scientist_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_missions_scientist_id', ['scientist_id'])

    # ### end Alembic commands ###
